bag/urls.py
from django.urls import path
from . import views

app_name = 'bag'  # This defines the namespace for the app

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    #path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('add/<int:item_id>/', views.add_to_bag, name='add_to_bag'),  # New pattern
    path('add/<int:product_id>/', views.add_to_bag, name='add_to_bag'),  # Old pattern
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

bake_boutique/urls.py
from .views import handler404
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),  # Admin site
    path('accounts/', include('allauth.urls')),  # django-allauth handles all account views
    path('', include('home.urls')),  # Home app URLs
    path('products/', include('products.urls')),  # Products app URLs
    path('bag/', include('bag.urls')),  # Bag app URLs
    path('checkout/', include('checkout.urls')),  # Checkout app URLs
    path('profile/', include('profiles.urls')),  # Profiles app URLs
    path('testimonials/', include('testimonials.urls')),  # Testimonials app URLs
    path('wishlist/', include('wishlist.urls')), # wishlist
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls', namespace='contact')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'bake_boutique.views.handler404'
handler403 = 'bake_boutique.views.handler403'
handler405 = 'bake_boutique.views.handler405'
handler500 = 'bake_boutique.views.handler500'

products/urls.py
from django.urls import path
from . import views

app_name = 'products'  # Ensure that the app_name is set to 'product'

urlpatterns = [
    path('', views.all_products, name='products'), #'products' URL
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'), # This is the URL for adding a product 
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('<int:product_id>/add_review/', views.add_review, name='add_review'),
    path('review/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('review/<int:review_id>/delete/', views.delete_review, name='delete_review'),

]

bag/views.py
from django.shortcuts import (
    render, redirect, reverse, HttpResponse, get_object_or_404
)
from django.contrib import messages

from products.models import Product


def view_bag(request):
    """ A view that renders the bag contents page """

    return render(request, 'bag/bag.html')


def add_to_bag(request, item_id):
    """ Add a quantity of the specified product to the shopping bag """

    product = get_object_or_404(Product, pk=item_id)
    quantity = int(request.POST.get('quantity', 1))# Default to 1 if quantity is not provided
    redirect_url = request.POST.get('redirect_url')
    size = None
    if 'product_size' in request.POST:
        size = request.POST['product_size']
    bag = request.session.get('bag', {})

    if size:
        if item_id in list(bag.keys()):
            if size in bag[item_id]['items_by_size'].keys():
                bag[item_id]['items_by_size'][size] += quantity
                messages.success(request,
                                 (f'Updated size {size.upper()} '
                                  f'{product.name} quantity to '
                                  f'{bag[item_id]["items_by_size"][size]}'))
            else:
                bag[item_id]['items_by_size'][size] = quantity
                messages.success(request,
                                 (f'Added size {size.upper()} '
                                  f'{product.name} to your bag'))
        else:
            bag[item_id] = {'items_by_size': {size: quantity}}
            messages.success(request,
                             (f'Added size {size.upper()} '
                              f'{product.name} to your bag'))
    else:
        if item_id in list(bag.keys()):
            bag[item_id] += quantity
            messages.success(request,
                             (f'Updated {product.name} '
                              f'quantity to {bag[item_id]}'))
        else:
            bag[item_id] = quantity
            messages.success(request, f'Added {product.name} to your bag')

    request.session['bag'] = bag
    return redirect(redirect_url)


def adjust_bag(request, item_id):
    """Adjust the quantity of the specified product to the specified amount"""

    product = get_object_or_404(Product, pk=item_id)
    quantity = int(request.POST.get('quantity'))
    size = None
    if 'product_size' in request.POST:
        size = request.POST['product_size']
    bag = request.session.get('bag', {})

    if size:
        if quantity > 0:
            bag[item_id]['items_by_size'][size] = quantity
            messages.success(request,
                             (f'Updated size {size.upper()} '
                              f'{product.name} quantity to '
                              f'{bag[item_id]["items_by_size"][size]}'))
        else:
            del bag[item_id]['items_by_size'][size]
            if not bag[item_id]['items_by_size']:
                bag.pop(item_id)
            messages.success(request,
                             (f'Removed size {size.upper()} '
                              f'{product.name} from your bag'))
    else:
        if quantity > 0:
            bag[item_id] = quantity
            messages.success(request,
                             (f'Updated {product.name} '
                              f'quantity to {bag[item_id]}'))
        else:
            bag.pop(item_id)
            messages.success(request,
                             (f'Removed {product.name} '
                              f'from your bag'))

    request.session['bag'] = bag
    return redirect(reverse('bag:view_bag'))


def remove_from_bag(request, item_id):
    """Remove the item from the shopping bag"""

    try:
        product = get_object_or_404(Product, pk=item_id)
        size = None
        if 'product_size' in request.POST:
            size = request.POST['product_size']
        bag = request.session.get('bag', {})

        if size:
            del bag[item_id]['items_by_size'][size]
            if not bag[item_id]['items_by_size']:
                bag.pop(item_id)
            messages.success(request,
                             (f'Removed size {size.upper()} '
                              f'{product.name} from your bag'))
        else:
            bag.pop(item_id)
            messages.success(request, f'Removed {product.name} from your bag')

        request.session['bag'] = bag
        return HttpResponse(status=200)

    except Exception as e:
        messages.error(request, f'Error removing item: {e}')
        return HttpResponse(status=500)

bag/templates/bag/bag-total.html
<h6><strong>Bag Total: ${{ total|floatformat:2 }}</strong></h6>
<h6>Delivery: ${{ delivery|floatformat:2 }}</h6>
<h4 class="mt-4"><strong>Grand Total: ${{ grand_total|floatformat:2 }}</strong></h4>
{% if free_delivery_delta > 0 %}
    <p class="mb-1 text-danger">
        You could get free delivery by spending just <strong>${{ free_delivery_delta }}</strong> more!
    </p>
{% endif %}

bag/templates/bag/bag.html
{% extends "base.html" %}
{% load static %}
{% load bag_tools %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container mb-2">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="logo-font mb-4">Shopping Bag</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col">
                {% if bag_items %}
                    <div class="d-block d-md-none">
                        <div class="row">
                            <div class="col">
                                {% include "bag/bag-total.html" %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                {% include "bag/checkout-buttons.html" %}
                                <p class="text-muted mb-5">A summary of your bag contents is below</p>
                            </div>
                        </div>
                        {% for item in bag_items %}
                            <div class="row">
                                <div class="col-12 col-sm-6 mb-2">
                                    {% include "bag/product-image.html" %}
                                </div>
                                <div class="col-12 col-sm-6 mb-2">
                                    {% include "bag/product-info.html" %}
                                </div>
                                <div class="col-12 col-sm-6 order-sm-last">
                                    <p class="my-0">Price Each: ${{ item.product.price }}</p>
                                    <p><strong>Subtotal: </strong>${{ item.product.price | calc_subtotal:item.quantity }}</p>
                                </div>
                                <div class="col-12 col-sm-6">
                                    {% include "bag/quantity-form.html" %}
                                </div>
                            </div>
                            <div class="row"><div class="col"><hr></div></div>
                        {% endfor %}
                        <div class="btt-button shadow-sm rounded-0 border border-black">
                            <a class="btt-link d-flex h-100">
                                <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
                            </a>	
                        </div>
                    </div>
                    <div class="table-responsive rounded d-none d-md-block">
                        <table class="table table-sm table-borderless">
                            <thead class="text-black">
                                <tr>
                                    <th scope="col">Product Info</th>
                                    <th scope="col"></th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Qty</th>
                                    <th scope="col">Subtotal</th>
                                </tr>
                            </thead>

                            {% for item in bag_items %}
                                <tr>
                                    <td class="p-3 w-25">
                                        {% include "bag/product-image.html" %}
                                    </td>
                                    <td class="py-3">
                                        {% include "bag/product-info.html" %}
                                    </td>
                                    <td class="py-3">
                                        <p class="my-0">${{ item.product.price }}</p>
                                    </td>
                                    <td class="py-3 w-25">
                                        {% include "bag/quantity-form.html" %}
                                    </td>
                                    <td class="py-3">
                                        <p class="my-0">${{ item.product.price | calc_subtotal:item.quantity }}</p>
                                    </td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="5" class="pt-5 text-right">
                                    {% include "bag/bag-total.html" %}
                                </td>
                            </tr>
                            <tr>
                                <td colspan="5" class="text-right">
                                    {% include "bag/checkout-buttons.html" %}
                                </td>
                            </tr>
                        </table>
                    </div>
                {% else %}
                    <p class="lead mb-5">Your bag is empty.</p>
                    <a href="{% url 'products:products' %}" class="btn btn-outline-black rounded-0 btn-lg">
                        <span class="icon">
                            <i class="fas fa-chevron-left"></i>
                        </span>
                        <span class="text-uppercase">Keep Shopping</span>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('.btt-link').click(function(e) {
        window.scrollTo(0,0)
    })
</script>
{% include 'products/includes/quantity_input_script.html' %}

<script type="text/javascript">
    // Update quantity on click
    $('.update-link').click(function(e) {
        var form = $(this).prev('.update-form');
        form.submit();
    })

    // Remove item and reload on click
    $('.remove-item').click(function(e) {
        var csrfToken = "{{ csrf_token }}";
        var itemId = $(this).attr('id').split('remove_')[1];
        var size = $(this).data('product_size');
        var url = `/bag/remove/${itemId}/`;
        var data = {'csrfmiddlewaretoken': csrfToken, 'product_size': size};

        $.post(url, data)
         .done(function() {
             location.reload();
         });
    })
</script>
{% endblock %}

bag/templates/bag/checkout-buttons.html
<a href="{% url 'products:products' %}" class="btn btn-outline-black rounded-0 btn-lg">
    <span class="icon">
        <i class="fas fa-chevron-left"></i>
    </span>
    <span class="text-uppercase">Keep Shopping</span>
</a>
<a href="{% url 'checkout' %}" class="btn btn-black rounded-0 btn-lg">
    <span class="text-uppercase">Secure Checkout</span>
    <span class="icon">
        <i class="fas fa-lock"></i>
    </span>
</a>

bag/templates/bag/product-image.html
{% if item.product.image %}
<img class="img-fluid rounded" src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
{% else %}
<img class="img-fluid rounded" src="{{ MEDIA_URL }}noimage.png" alt="{{ item.product.name }}">
{% endif %}

bag/templates/bag/product-info.html
<p class="my-0"><strong>{{ item.product.name }}</strong></p>
<p class="my-0"><strong>Size: </strong>{% if item.product.has_sizes %}{{ item.size|upper }}{% else %}N/A{% endif %}</p>
<p class="my-0 small text-muted">SKU: {{ item.product.sku|upper }}</p>

bag/templates/bag/quantity-form.html
<form class="form update-form" method="POST" action="{% url 'bag:adjust_bag' item.item_id %}">
    {% csrf_token %}
    <div class="form-group">
        <div class="input-group">
            <div class="input-group-prepend">
                <button class="decrement-qty btn btn-sm btn-black rounded-0" 
                    data-item_id="{{ item.item_id }}" id="decrement-qty_{{ item.item_id }}">
                    <span>
                        <i class="fas fa-minus fa-sm"></i>
                    </span>
                </button>
            </div>
            <input class="form-control form-control-sm qty_input" type="number"
                name="quantity" value="{{ item.quantity }}" min="1" max="99"
                data-item_id="{{ item.item_id }}"
                id="id_qty_{{ item.item_id }}">
            <div class="input-group-append">
                <button class="increment-qty btn btn-sm btn-black rounded-0"
                    data-item_id="{{ item.item_id }}" id="increment-qty_{{ item.item_id }}">
                    <span>
                        <i class="fas fa-plus fa-sm"></i>
                    </span>
                </button>
            </div>
            {% if item.product.has_sizes %}
                <input type="hidden" name="product_size" value="{{ item.size }}">
            {% endif %}
        </div>
    </div>
</form>
<a class="update-link text-info"><small>Update</small></a>
<a class="remove-item text-danger float-right" id="remove_{{ item.item_id }}" data-product_size="{{ item.size }}"><small>Remove</small></a>