bag/urls.py
from django.urls import path
from . import views

app_name = 'bag'  # This defines the namespace for the app

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    #path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('add/<int:item_id>/', views.add_to_bag, name='add_to_bag'),  # New pattern
    path('add/<int:product_id>/', views.add_to_bag, name='add_to_bag'),  # Old pattern
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

bake_boutique/urls.py
from .views import handler404
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),  # Admin site
    path('accounts/', include('allauth.urls')),  # django-allauth handles all account views
    path('', include('home.urls')),  # Home app URLs
    path('products/', include('products.urls')),  # Products app URLs
    path('bag/', include('bag.urls')),  # Bag app URLs
    path('checkout/', include('checkout.urls')),  # Checkout app URLs
    path('profile/', include('profiles.urls')),  # Profiles app URLs
    path('testimonials/', include('testimonials.urls')),  # Testimonials app URLs
    path('wishlist/', include('wishlist.urls')), # wishlist
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls', namespace='contact')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'bake_boutique.views.handler404'
handler403 = 'bake_boutique.views.handler403'
handler405 = 'bake_boutique.views.handler405'
handler500 = 'bake_boutique.views.handler500'

products/urls.py
from django.urls import path
from . import views

app_name = 'products'  # Ensure that the app_name is set to 'product'

urlpatterns = [
    path('', views.all_products, name='products'), #'products' URL
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'), # This is the URL for adding a product 
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('<int:product_id>/add_review/', views.add_review, name='add_review'),
    path('review/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('review/<int:review_id>/delete/', views.delete_review, name='delete_review'),

]

wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('', views.view_wishlist, name='view_wishlist'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>

    {% block meta %}
    <!-- Required meta tags -->
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- SEO Meta Tags -->
    <meta name="description" content="Shop the finest baked goods, from fresh cakes to muffins, delivered straight to your door. Order online at Bake Boutique today!">
    <meta name="keywords" content="bake boutique, online bakery, fresh cakes, muffins, cookies, order bakery online, best bakery, custom cakes, sweet treats, dessert delivery">
    {% endblock %}

    {% block extra_meta %}
    {% endblock %}

    {% block corecss %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link
        href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endblock %}

    {% block extra_css %}
    {% endblock %}

    {% block corejs %}
    <script src="https://kit.fontawesome.com/4892267aa3.js" crossorigin="anonymous"></script><!--font awsome kit-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
        integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
        crossorigin="anonymous"></script>
    <!-- Stripe -->
    <script src="https://js.stripe.com/v3/"></script>
    {% endblock %}

    {% block extra_js %}
    {% endblock %}

    <title>Bake Boutique {% block extra_title %}{% endblock %}</title>
</head>

<body>
    <header class="container-fluid fixed-top">
     <div class="container"> 
        <div class="row">
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0 text-center text-lg-left">
                 
                <a href="{% url 'products:products' %}" class="nav-link main-logo-link">

                    <h2 class="logo-font text-black my-0"><strong>Bake</strong> Boutique</h2>
                </a>
            </div>
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0">
                 
                 <form method="GET" action="{% url 'products:products' %}">

                    <div class="input-group w-100">
                        <input class="form-control border border-black rounded-0" type="text" name="q"
                            placeholder="Search our site">
                        <div class="input-group-append">
                            <button class="form-control btn btn-black border border-black rounded-0" type="submit">
                                <span class="icon">
                                    <i class="fas fa-search"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- Desktop Only: My Account / Wishlist / Bag -->
<div class="col-12 col-lg-4 my-auto py-1 py-lg-0 d-none d-lg-block">
    <ul class="list-inline list-unstyled text-center text-lg-right my-0">
        <!-- My Account Section -->
        <li class="list-inline-item dropdown">
            <a class="text-black nav-link" href="#" id="user-options" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <div class="text-center">
                    <div><i class="fas fa-user fa-lg"></i></div>
                    <p class="my-0">My Account</p>
                </div>
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="user-options">
                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                        <a href="{% url 'products:add_product' %}" class="dropdown-item">Product Management</a>
                    {% endif %}
                    <a href="{% url 'profile' %}" class="dropdown-item">My Profile</a>
                    <a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a>
                {% else %}
                    <a href="{% url 'account_signup' %}" class="dropdown-item">Register</a>
                    <a href="{% url 'account_login' %}" class="dropdown-item">Login</a>
                {% endif %}
            </div>
        </li>
        {% if user.is_authenticated %}
        <li class="list-inline-item">
            <a class="list-inline-item" href="{% url 'wishlist:view_wishlist' %}">
                <div class="text-center">
                    <div><i class="fas fa-heart fa-lg"></i></div>
                    <p class="my-0">Wishlist</p>
                </div>
            </a>
        </li>
        {% endif %}
        <li class="list-inline-item">
            <a class="{% if grand_total %}text-info font-weight-bold{% else %}text-black{% endif %} nav-link"
                href="{% url 'bag:view_bag' %}">
                <div class="text-center">
                    <div><i class="fas fa-shopping-bag fa-lg"></i></div>
                    <p class="my-0">
                        {% if grand_total %}
                            ${{ grand_total|floatformat:2 }}
                        {% else %}
                            $0.00
                        {% endif %}
                    </p>
                </div>
            </a>
        </li>
    </ul>
</div>
        </div>
        
        <div class="row bg-white"></div>
            <nav class="navbar navbar-expand-lg navbar-light w-100">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Mobile & Tablet Only -->
                <div class="col-12 d-block d-lg-none">
                    {% include 'includes/mobile-top-header.html' %}
                </div>

                {% include 'includes/main-nav.html' %}
            </nav>
        </div>
        <div id="delivery-banner" class="row text-center">
            <div class="col bg-black text-white">
                <h4 class="logo-font my-1">Get Free delivery for orders over €{{ free_delivery_threshold }}!!</h4>                
            </div>            
        </div>
    </div>
    </header>

    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
                {% with message.level as level %}
                    {% if level == 40 %}
                        {% include 'includes/toasts/toast_error.html' %}
                    {% elif level == 30 %}
                        {% include 'includes/toasts/toast_warning.html' %}
                    {% elif level == 25 %}
                        {% include 'includes/toasts/toast_success.html' %}
                    {% else %}
                        {% include 'includes/toasts/toast_info.html' %}
                    {% endif %}
                {% endwith %}
            {% endfor %}
    </div>
    {% endif %}

<main class="container header-container">
    {% block page_header %}
    {% endblock %}

    {% block content %}
    {% endblock %}
</main>


    {% block postloadjs %}
    <script type="text/javascript">
        $('.toast').toast('show');
    </script>
    {% endblock %}


</body>
<!-------------------------- Footer ------------------->
<!-- Footer facebook -->
<footer class="container-wrapper">
    <div class="container quotes-container content-container">
      <section class="footer">
        <div class="row">
            <div class="col-12 page-header mb-4">
                <h2 class="text-uppercase">Stay in touch:</h2>
                <hr class="block-divider block-divider--short">
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <h3>Social</h3>
                <p>Keep up to date with all our latest offers</p>
                <a href="https://www.facebook.com/profile.php?id=61574437315834" target="_blank"><i class="fab fa-facebook-square"></i> Follow us on Facebook!</a>
                <br>
                <!-- Privacy Policy -->
        <!--# Credit: https://www.privacypolicygenerator.info/ -->
                <a href="https://www.termsfeed.com/live/6ffb5919-94bb-4c20-8806-5586324de83d" target="_blank">Privacy Policy</a>
            </div>
    
            <div class="col-12 col-md-6">
                <h2>Subscribe!</h2>
                <p>Get exclusive offers and discount codes by subscribing to our monthly newsletter</p>
             <!-- Footer Signup form  -->
        <!--# Credit: https://us16.admin.mailchimp.com/audience/contacts?id=657668-->
            <div id="mc_embed_shell">
                <link href="//cdn-images.mailchimp.com/embedcode/classic-061523.css" rel="stylesheet" type="text/css">
            <style type="text/css">
                #mc_embed_signup{false;clear:left; font:14px Helvetica,Arial,sans-serif; width:auto;}
              
            </style>
      <div id="mc_embed_signup">
          <form action="https://herokuapp.us16.list-manage.com/subscribe/post?u=d3b362119ab1b1649c02042b2&amp;id=e5b0bbba54&amp;f_id=00730be0f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
              <div id="mc_embed_signup_scroll">
                  <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
                  <div class="mc-field-group"><label for="mce-EMAIL">Email Address <span class="asterisk">*</span></label><input type="email" name="EMAIL" class="required email" id="mce-EMAIL" required="" value=""></div>
              <div id="mce-responses" class="clear foot">
                  <div class="response" id="mce-error-response" style="display: none;"></div>
                  <div class="response" id="mce-success-response" style="display: none;"></div>
              </div>
          <div style="position: absolute; left: -5000px;" aria-hidden="true">
              /* real people should not fill this in and expect good things - do not remove this or risk form bot signups */
              <input type="text" name="b_d3b362119ab1b1649c02042b2_e5b0bbba54" tabindex="-1" value="">
          </div>
              <div class="optionalParent">
                  <div class="clear foot">
                      <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button" value="Subscribe">
                      <p style="margin: 0px auto;"><a href="http://eepurl.com/jakoeU" title="Mailchimp - email marketing made easy and fun"><span style="display: inline-block; background-color: transparent; border-radius: 4px;"><img class="refferal_badge" src="https://digitalasset.intuit.com/render/content/dam/intuit/mc-fe/en_us/images/intuit-mc-rewards-text-dark.svg" alt="Intuit Mailchimp" style="width: 220px; height: 40px; display: flex; padding: 2px 0px; justify-content: center; align-items: center;"></span></a></p>
                  </div>
              </div>
          </div>
         </form>
      </div>
      <script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"></script><script type="text/javascript">(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';fnames[6]='COMPANY';ftypes[6]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script></div>
      
         </div>
       </div>
       <p>
        Developed By Tatenda Mudehwe | Code Institute's Portfolio Project 5 - 2025
    </p>
       
     </section> 
   </div>
 </footer>
               

<!-- Font Awesome Kit -->
<script src="https://kit.fontawesome.com/4892267aa3.js" crossorigin="anonymous"></script>


</html>